### PR TITLE
Open camera or gallery automatically

### PR DESCRIPTION
**Pull request by mgroeneweg**
Open camera or gallery automatically. Cleaned up widget code to shut up lint/hint.
Upgraded test project to Mx5.21.5 because it choked on the offlineCapable attribute in the widget XML
Enhanced test project to open camera or gallery.

### CODE REVIEW

**Comment by mgroeneweg** [comment]
This has been left waiting so long it now is in conflict. Any chance on this pull request being merged?

**Comment by Andries-Smit** [comment]
Auto capture is added to the widget and released in the appstore version 4.0
The CSRF token fix is no longer relevant for the latest version.

**Comment by mgroeneweg** [comment]
Great! I will test tomorrow

**Comment by mgroeneweg** [comment]
Works great! Tested with Mx7.13.1

**Pull request closed without merging**
